### ISSUE TITLE
Marked Texts not translated

### ISSUE THREAD

**Issue by primus852** [biesbjerg/ngx-translate-extract-marker#4]
I have a strange issue and I am not sure if this is related to the extractor/marker (this package) or to ngx-translate/core, but I suspect it is this package.

As per your README I added

`import {marker as TRANSLATE} from '@biesbjerg/ngx-translate-extract-marker';`

to my Component and created a variable to translate: 

`atTime = TRANSLATE('g.txt.various.atTime');`

Everything compiles but my in my html it only shows the id `g.txt.various.atTime`

Demo here, https://stackblitz.com/edit/angular-hxri9n is this a bug or am I doing something wrong?

cheers

**Comment by ismailcherri** [comment]
You need to add the translate pipe to your component html.
e.g.
`{{atTime | translate}}`

**Comment by primus852** [comment]
I updated the StackBlitz with your comment, but now nothing shows in the rendered html. Any ideas

**Comment by biesbjerg** [comment]
This package is just a marker to let ngx-translate-extract know it should extract the string. It doesn't do any actually translating of the string, that's the responsibility for ngx-translate. 

Like @ismailcherri says, you would still need to pass the string returned by the marker through TranslateService or use the translate pipe in your template.

In your stackblitz it seems de.json isn't loaded properly (Check Chrome network requests).
